version: '3.8'
services:
  grpc:
    build:
      context: .
      dockerfile: GrpcService/Dockerfile
    ports:
      - "8003:8003"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - api-network

networks:
  api-network:
    driver: bridge
